### ISSUE TITLE
wrong language tag

### ISSUE THREAD

**Issue by ghost** [zorgiepoo/Sky-Checkers#1]
The project is specified to be C language. As one or more compilation units use C++ specific features that are not available to C. please alter the language from C to C++. Alternatively, change the code so that it DOES compile with a C compiler.

**Comment by zorgiepoo** [comment]
Most of the code is in C. Having only one C++ source file (which is only for Windows to interface with a system library, and not for the other 4 platforms) does not make it a "C++ project"

This doesn't sound like a very important issue either way. I wrote this project for myself and my friends, and just happen to host the source here. I'm surprised you found it and wanted to nitpick this (assuming this is not a bot).
